// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOFlITphm95vhNajBWN4KcgvUpwWl3KFk',
    appId: '1:63824746258:web:047983607355413eb145cb',
    messagingSenderId: '63824746258',
    projectId: 'locum-10af1',
    authDomain: 'locum-10af1.firebaseapp.com',
    storageBucket: 'locum-10af1.appspot.com',
    measurementId: 'G-PJGKR78EGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQcLAGkD1K1fjFgi_wT9USz23s4_fRsjs',
    appId: '1:63824746258:android:1dd6d7bceba3fc8eb145cb',
    messagingSenderId: '63824746258',
    projectId: 'locum-10af1',
    storageBucket: 'locum-10af1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU2qWItTNbLMwqoewWcx5bkIB6aNga9wo',
    appId: '1:63824746258:ios:9914c8554863c76ab145cb',
    messagingSenderId: '63824746258',
    projectId: 'locum-10af1',
    storageBucket: 'locum-10af1.appspot.com',
    iosBundleId: 'com.example.locumspherelimitedUnit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU2qWItTNbLMwqoewWcx5bkIB6aNga9wo',
    appId: '1:63824746258:ios:c2feb5255cbdf179b145cb',
    messagingSenderId: '63824746258',
    projectId: 'locum-10af1',
    storageBucket: 'locum-10af1.appspot.com',
    iosBundleId: 'com.example.locumspherelimitedUnit.RunnerTests',
  );
}
